version: "3"

services:

  # test:
  #   build:
  #     context: .
  #     args:
  #       TZ: Europe/Berlin
  #   restart: "no"
  #   hostname: playground
  #   depends_on:
  #     - influx
  #   volumes:
  #     - ./:/opt/playground/
  #   working_dir: "/opt/playground"
  #   command: ["/usr/bin/wait-for-it.sh", "influx:8086", "--", "node", "build/playground/playground.js"]

  grafana:
    build:
      context: ./test-env/grafana
      args:
        TZ: Europe/Berlin
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-logs:/var/log/grafana
    ports:
      - "3000:3000"
    restart: "no"
    hostname: grafana
    depends_on:
      - influx

  influx:
    build:
      context: ./test-env/influx
      args:
        TZ: Europe/Berlin
    volumes:
      - influx-data:/var/lib/influxdb
      - influx-logs:/var/log/influxdb
    ports:
      - "8086:8086"
    restart: "no"
    hostname: influx

volumes:
  influx-data:
  influx-logs:
  grafana-data:
  grafana-logs:
