version: "3"

services:

  node6:
    build:
      context: ./test
      dockerfile: Dockerfile-node6
    user: "node"
    entrypoint: "/opt/inspector-influx/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-influx/
    working_dir: "/opt/inspector-influx"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-influx/.tmp/.npm/"
      - NODE_VERSION=6

  node7:
    build:
      context: ./test
      dockerfile: Dockerfile-node7
    user: "node"
    entrypoint: "/opt/inspector-influx/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-influx/
    working_dir: "/opt/inspector-influx"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-influx/.tmp/.npm/"
      - NODE_VERSION=7

  node8:
    build:
      context: ./test
      dockerfile: Dockerfile-node8
    user: "node"
    entrypoint: "/opt/inspector-influx/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-influx/
    working_dir: "/opt/inspector-influx"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-influx/.tmp/.npm/"
      - NODE_VERSION=8

  node9:
    build:
      context: ./test
      dockerfile: Dockerfile-node9
    user: "node"
    entrypoint: "/opt/inspector-influx/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-influx/
    working_dir: "/opt/inspector-influx"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-influx/.tmp/.npm/"
      - NODE_VERSION=9

  node10:
    build:
      context: ./test
      dockerfile: Dockerfile-node10
    user: "node"
    entrypoint: "/opt/inspector-influx/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-influx/
    working_dir: "/opt/inspector-influx"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-influx/.tmp/.npm/"
      - NODE_VERSION=10

  node11:
    build:
      context: ./test
      dockerfile: Dockerfile-node11
    user: "node"
    entrypoint: "/opt/inspector-influx/test/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-influx/
    working_dir: "/opt/inspector-influx"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-influx/.tmp/.npm/"
      - NODE_VERSION=11

  # test:
  #   build:
  #     context: ./test-env
  #     args:
  #       TZ: Europe/Berlin
  #   restart: "no"
  #   hostname: playground
  #   depends_on:
  #     - influx
  #   volumes:
  #     - ./:/opt/playground/
  #   working_dir: "/opt/playground"
  #   command: ["/usr/bin/wait-for-it.sh", "influx:8086", "--", "node", "build/playground/playground.js"]

  grafana:
    build:
      context: ./test-env/grafana
      args:
        TZ: Europe/Berlin
    volumes:
      - ./test-env/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./test-env/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./playground/dashboards:/dashboards
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      default:
        aliases:
         - grafana
    hostname: grafana
    depends_on:
      - influx

  influx:
    build:
      context: ./test-env/influx
      args:
        TZ: Europe/Berlin
    volumes:
      - influx-data:/var/lib/influxdb
      - influx-logs:/var/log/influxdb
    ports:
      - "8086:8086"
    restart: "no"
    hostname: influx

volumes:
  influx-data:
  influx-logs:
