apiVersion: 1

# see http://docs.grafana.org/administration/provisioning/
datasources:
- name: influxdb
  type: influxdb
  access: proxy
  url: http://influx:8086
  isDefault: true
  editable: true
  database: example-db
  user: admin
  password: admin
